(define (product a b)
  (define (even? x) (= (remainder x 2) 0))
  (define (double x) (* x 2))
  (define (halve x) (/ x 2))
  (define (product-iter a b c)
	(cond (( = b 0 ) c )
		  ((even? b) (product-iter (double a) (halve b) c))
		  (else (product-iter a (- b 1) (+ c a)))))
  (product-iter a b 0))
