(define (sum term a next b)
  (if (> a b)
	  0
	  (+ (term a)
		 (sum term (next a) next b))))
(define (cube x) (* x x x))
(define (inc x) (+ x 1))
(define (sum-itergers a b)
  (define (identity x) x)
  (sum identity a inc b))
(define (sum-cubes a b)
  (sum cube a inc b))
(define (intergral f a b dx)
  (define (add-dx x) (+ x dx))
  (* (sum f (+ a (/ dx 2.0)) add-dx b)
	 dx))
